### ISSUE TITLE
Request for asm documentation

### ISSUE THREAD

**Issue by cyberkm** [mattgodbolt/gcc-explorer#89] opened 2015-11-03 21:59 UTC
It will be really great if one could hover over asm instruction and see its documentation from chip manufacturer site, in a tooltip or a link to the instruction documentation in a new window/tab.

**Comment by mattgodbolt** [comment] 2015-11-03 22:00
Thanks for the suggestion. I believe this is a duplicate of #30

**Closed by mattgodbolt** 2015-11-03 22:00 UTC

**Comment by cyberkm** [comment] 2015-11-03 22:02
Yep, thats a duplicate.
Any plans to implement it?
I see it was opened several years ago.

**Comment by mattgodbolt** [comment] 2015-11-04 03:07
It's on the list...I'll be honest I don't have firm plans to implement it
any time soon but clearly more and more people are asking for it! :)

On Tue, Nov 3, 2015 at 4:02 PM, Pavel Bibergal <notifications@github.com>
wrote:

> Yep, thats a duplicate.
> Any plans to implement it?
> I see it was opened several years ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/gcc-explorer/issues/89#issuecomment-153503516>
> .
>



-- 
Matt
