### ISSUE TITLE
Assembly code disappears for Rust if I add optimization

### ISSUE THREAD

**Issue by vi** [mattgodbolt/gcc-explorer#209] opened 2016-12-17 02:37 UTC
With `--crate-type staticlib -C opt-level=0` I see things on the right panel, but with `--crate-type staticlib -C opt-level=1` it shows nothing.

Maybe default example source code should have `#[no_mangle]`?:

```
// Type your code here, or load an example.

#[no_mangle]
pub fn square(num: i32) -> i32 {
  num * num
}
```

**Comment by mattgodbolt** [comment] 2016-12-19 13:01
Duplicate of #139

**Closed by mattgodbolt** 2016-12-19 13:01 UTC
