### ISSUE TITLE
Diff.

### ISSUE THREAD

**Issue by vadimgit** [mattgodbolt/gcc-explorer#109] opened 2016-03-16 00:34 UTC
Diff and history would be great to see. Or may be just highlight last changes.

**Comment by mattgodbolt** [comment] 2016-03-16 16:38
Thanks for the feedback: highlighting last changes is a great idea.

See also #9, #1 and #15

**Comment by mattgodbolt** [comment] 2016-10-07 22:26
Closing this as a duplicate of #9

**Closed by mattgodbolt** 2016-10-07 22:26 UTC
Labels: enhancement
